### PR TITLE
enforce user 1000 group 1000 #305

### PR DESCRIPTION
**Pull request by alanbraz**
in Dockerfiles and docker-compose.yaml files

### CODE REVIEW

**Comment by costrouc** [comment]
@alanbraz I had to add a bit to make this PR pass would you mind adding to the Dockerfile

```
RUN chown -R 1000:1000 /opt/conda/pkgs && \
    mkdir -p /var/lib/conda-store && \
    chown 1000:1000 /var/lib/conda-store && \
    mkdir -p /opt/conda-store/envs && \
    chown 1000:1000 /opt/conda-store/envs

WORKDIR /var/lib/conda-store
```

**Comment by alanbraz** [comment]
in which one of the Dockerfiles??? conda-store or conda-store-server??

**Comment by costrouc** [comment]
conda-store-server

**Comment by alanbraz** [comment]
done

**Review by costrouc — APPROVED** [review]
Thanks @alanbraz! Appreciate your contribution and great meeting you at SciPy!

**Pull request merged**
